# Generated by Django 5.0.2 on 2025-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('caminho', models.CharField(max_length=100)),
                ('unidade_sigla', models.CharField(max_length=10)),
                ('unidade_nome', models.CharField(max_length=100)),
            ],
        ),
    ]
