# Generated by Django 5.0.2 on 2025-09-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=100, null=True)),
                ('nome_servidor', models.CharField(blank=True, db_column='NOME_SERVIDOR', max_length=100, null=True)),
                ('mes', models.CharField(blank=True, db_column='MES', max_length=100, null=True)),
                ('vinculo_servidor', models.CharField(blank=True, db_column='VINCULO_SERVIDOR', max_length=100, null=True)),
                ('situacao_funcional', models.CharField(blank=True, db_column='SITUACAO_FUNCIONAL', max_length=100, null=True)),
                ('situacao_vinculo', models.CharField(blank=True, db_column='SITUACAO_VINCULO', max_length=100, null=True)),
                ('cod_uorg', models.CharField(blank=True, db_column='COD_UORG', max_length=100, null=True)),
                ('uorg', models.CharField(blank=True, db_column='UORG', max_length=100, null=True)),
                ('grupo_uorg', models.CharField(blank=True, db_column='GRUPO_UORG', max_length=100, null=True)),
                ('nivel_funcao', models.CharField(blank=True, db_column='NIVEL_FUNCAO', max_length=100, null=True)),
                ('jornada_trabalho', models.CharField(blank=True, db_column='JORNADA_TRABALHO', max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, db_column='CARGO', max_length=100, null=True)),
                ('data_ingresso_cargo', models.CharField(blank=True, db_column='DATA_INGRESSO_CARGO', max_length=100, null=True)),
                ('sistematica_cargo', models.CharField(blank=True, db_column='SISTEMATICA_CARGO', max_length=100, null=True)),
                ('nivel_cargo', models.CharField(blank=True, db_column='NIVEL_CARGO', max_length=100, null=True)),
                ('gr_niv_cargo', models.CharField(blank=True, db_column='GR_NIV_CARGO', max_length=100, null=True)),
                ('cod_cargo', models.CharField(blank=True, db_column='COD_CARGO', max_length=100, null=True)),
                ('classe_cargo', models.CharField(blank=True, db_column='CLASSE_CARGO', max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, db_column='SEXO', max_length=100, null=True)),
                ('cod_orgao', models.IntegerField(blank=True, db_column='COD_ORGAO', null=True)),
                ('nome_uorg', models.CharField(blank=True, db_column='NOME_UORG', max_length=100, null=True)),
                ('cod_siorg_orgao', models.IntegerField(blank=True, db_column='COD_SIORG_ORGAO', null=True)),
                ('cod_siorg_uorg', models.IntegerField(blank=True, db_column='COD_SIORG_UORG', null=True)),
                ('cod_vaga', models.IntegerField(blank=True, db_column='COD_VAGA', null=True)),
                ('data_nascimento_servidor', models.CharField(blank=True, db_column='DATA_NASCIMENTO_SERVIDOR', max_length=100, null=True)),
                ('deficiencia_fisica', models.CharField(blank=True, db_column='DEFICIENCIA_FISICA', max_length=100, null=True)),
                ('escolaridade', models.CharField(blank=True, db_column='ESCOLARIDADE', max_length=100, null=True)),
                ('grupo_escolaridade', models.CharField(blank=True, db_column='GRUPO_ESCOLARIDADE', max_length=100, null=True)),
                ('cor_origem_etnica', models.CharField(blank=True, db_column='COR_ORIGEM_ETNICA', max_length=100, null=True)),
                ('grupo_situacao_vinculo', models.CharField(blank=True, db_column='GRUPO_SITUACAO_VINCULO', max_length=100, null=True)),
                ('ano_ing_spub', models.CharField(blank=True, db_column='ANO_ING_SPUB', max_length=100, null=True)),
                ('exclusao', models.CharField(blank=True, db_column='EXCLUSAO', max_length=100, null=True)),
                ('dia_nomeacao', models.CharField(blank=True, db_column='DIA_NOMEACAO', max_length=100, null=True)),
                ('dia_ocor_ingr_orgao_ev', models.CharField(blank=True, db_column='DIA_OCOR_INGR_ORGAO_EV', max_length=100, null=True)),
                ('dia_ocor_excl_serv_ev', models.CharField(blank=True, db_column='DIA_OCOR_EXCL_SERV_EV', max_length=100, null=True)),
                ('atividade_funcao', models.CharField(blank=True, db_column='ATIVIDADE_FUNCAO', max_length=100, null=True)),
                ('qtde_vinc_serv', models.IntegerField(blank=True, db_column='QTDE_VINC_SERV', null=True)),
                ('qtde_afastamento', models.FloatField(blank=True, db_column='QTDE_AFASTAMENTO', null=True)),
                ('mes_ansi', models.CharField(blank=True, db_column='MES_ANSI', max_length=100, null=True)),
                ('siape', models.CharField(blank=True, db_column='SIAPE', max_length=100, null=True)),
                ('id', models.CharField(db_column='ID', max_length=100, primary_key=True, serialize=False)),
                ('carreira', models.CharField(blank=True, db_column='CARREIRA', max_length=100, null=True)),
                ('escolaridade2', models.CharField(blank=True, db_column='ESCOLARIDADE2', max_length=100, null=True)),
                ('idade', models.IntegerField(blank=True, db_column='IDADE', null=True)),
                ('faixa_etaria', models.CharField(blank=True, db_column='FAIXA_ETARIA', max_length=100, null=True)),
                ('cod_afastamento', models.CharField(blank=True, db_column='COD_AFASTAMENTO', max_length=100, null=True)),
                ('dia_inicio_afastamento', models.CharField(blank=True, db_column='DIA_INICIO_AFASTAMENTO', max_length=10, null=True)),
                ('dia_fim_afastamento', models.CharField(blank=True, db_column='DIA_FIM_AFASTAMENTO', max_length=10, null=True)),
                ('caminho', models.CharField(blank=True, max_length=100, null=True)),
                ('unidade_sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('unidade_nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'core_servidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servidor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='NOME', max_length=100)),
                ('siape', models.CharField(db_column='SIAPE', max_length=100)),
            ],
            options={
                'db_table': 'servidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('caminho', models.CharField(max_length=100)),
                ('caminho_sigla', models.CharField(blank=True, max_length=100, null=True)),
                ('unidade_sigla', models.CharField(max_length=10)),
                ('unidade_nome', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Setor2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.setor',),
        ),
    ]
